name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install pipenv
      run: |
        curl https://pyenv.run | bash
      shell: bash

    - name: Install pipenv
      run: |
        pip install pipenv
      shell: bash

    - name: Install dependencies with pipenv
      run: |
        pipenv install --deploy --ignore-pipfile
        pipenv install setuptools
      shell: bash
    - name: Extract version number
      id: version_number
      run: echo "{VERSION_NUMBER}={1.0.${{github.run_number}}}" >> $GITHUB_OUTPUT
    - name: Update version in setup.py
      run: >-
        sed -e "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag.outputs.VERSION_NUMBER }}/g" setup.py
    - name: Run tests
      run: pipenv run python -m unittest discover tests
    - name: Build Source and Wheel Distributions
      run: |
        pipenv run python setup.py sdist bdist_wheel
    - name: Publish Distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
