name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install pipenv
      run: |
        curl https://pyenv.run | bash
      shell: bash

    - name: Install pipenv
      run: |
        pip install pipenv
      shell: bash

    - name: Install dependencies with pipenv
      run: |
        pipenv install --deploy --ignore-pipfile
      shell: bash

    - name: Run tests
      run: pipenv run python -m unittest discover tests

  #  - name: Publish to PyPI
  #    env:
  #      TWINE_USERNAME: __token__
  #      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
  #    run: |
  #      pipenv run python setup.py sdist bdist_wheel
  #      pipenv run python -m pip install twine
  #      pipenv run python -m twine upload --repository pypi dist/*
