name: Validate Pull Request

on:
  pull_request:
    branches:
      - main
      - fix/**
      - feature/**
      - chore/**
      - doc/**

jobs:
  build_on_pull_request:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install pipenv
      run: |
        curl https://pyenv.run | bash
      shell: bash

    - name: Install pipenv
      run: |
        pip install pipenv
      shell: bash

    - name: Install dependencies with pipenv
      run: |
        pipenv install --deploy --ignore-pipfile
        pipenv install setuptools

    - name: Install Compose
      uses: ndeloof/install-compose-action@v0.0.1
      with:
        version: v2.1.0 # defaults to 'latest'
        legacy: true    # will also install in PATH as `docker-compose`
        run: docker-compose --version
#    - name: Start containers
#      run: docker run  -d -e RABBITMQ_DEFAULT_USER=rabbitmq -e RABBITMQ_DEFAULT_PASS=rabbitmq -p 15672:15672 -p 5672:5672 --name rabbit-test  rabbitmq:3-management
#      shell: bash
    - name: Start containers
      run: ~/.docker/cli-plugins/docker-compose -f "docker-compose.yml" up -d --force-recreate
    - name: Run tests
      run: pipenv run python -m coverage run -m unittest tests/**
    - name: generate xml coverage
      run: pipenv run python -m coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#    - name: Stop containers
#      if: always()
#      run: docker rm rabbit-test
#      shell: bash
    - name: Stop containers
      if: always()
      run: ~/.docker/cli-plugins/docker-compose down
